name: devel
on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 */5 * * *' # At minute 0 past every 5th hour UTC

jobs:
  test:
    name: Notifier
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Check
        env:
          CYPRESS_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CYPRESS_TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          yarn
          yarn cy:run
